### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by ersivv** [li-xiaoqing/perfect-markdown#21]
Please add multilanguage support i18n

**Comment by li-xiaoqing** [comment]
Thank you for your issue, i will consider adding this feature.

**Comment by raul-sauco** [comment]
Any progress with this issue? I could help with this if help is wanted.

**Comment by maltegrosse** [comment]
any progress on this? English language would be appreciated...

**Comment by li-xiaoqing** [comment]
v1.1.0 support i18n
